# Site settings
title: 개발자 최명지
url: "https://choimyungji.github.io"
baseurl: ""
description: >
    개발자 최명지의 위키입니다.

# My information
email: choimyungji@gmail.com
author: 최명지
profile: ㅇㅇ 
twitter_username: maeng4u 
github_username: choimyungji 
# comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/_posts"
paginate_path: "/_posts/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/
    thoughts:
        output: true
        permalink: /:collection/:path/
    posts:
        output: true
        permalink: /:collection/:path/

# Comment Service
# disqus:
#   id: choimyungji 
#   shortname: choimyungji 
# utterances:
#   repo: choimyungji/choimyungji.github.io
#   issue-term: pathname
#   label: Comment
#   branch: master

google_analytics:
  ua: UA-125415151-1

# google_adsense:
#   client: ca-pub-3675948545737694

blame: "https://github.com/choimyungji/choimyungji.github.io/blame/master/_wiki"
edit: "https://github.com/choimyungji/choimyungji.github.io/edit/master/_wiki"
issue: "https://github.com/choimyungji/choimyungji.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
